/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedResourcesRouteImport } from './routes/_authed/resources'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedOnboardRouteImport } from './routes/_authed/onboard'
import { Route as AuthedLandingRouteImport } from './routes/_authed/landing'
import { Route as AuthedDirectoryRouteImport } from './routes/_authed/directory'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedDirectoryIndexRouteImport } from './routes/_authed/directory/index'
import { Route as AuthedDirectoryUserIdRouteImport } from './routes/_authed/directory/$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedResourcesRoute = AuthedResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardRoute = AuthedOnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLandingRoute = AuthedLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDirectoryRoute = AuthedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDirectoryIndexRoute = AuthedDirectoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDirectoryRoute,
} as any)
const AuthedDirectoryUserIdRoute = AuthedDirectoryUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AuthedDirectoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/directory': typeof AuthedDirectoryRouteWithChildren
  '/landing': typeof AuthedLandingRoute
  '/onboard': typeof AuthedOnboardRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/profile': typeof AuthedProfileRoute
  '/resources': typeof AuthedResourcesRoute
  '/directory/$userId': typeof AuthedDirectoryUserIdRoute
  '/directory/': typeof AuthedDirectoryIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/landing': typeof AuthedLandingRoute
  '/onboard': typeof AuthedOnboardRoute
  '/onboarding': typeof AuthedOnboardingRoute
  '/profile': typeof AuthedProfileRoute
  '/resources': typeof AuthedResourcesRoute
  '/': typeof AuthedIndexRoute
  '/directory/$userId': typeof AuthedDirectoryUserIdRoute
  '/directory': typeof AuthedDirectoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/directory': typeof AuthedDirectoryRouteWithChildren
  '/_authed/landing': typeof AuthedLandingRoute
  '/_authed/onboard': typeof AuthedOnboardRoute
  '/_authed/onboarding': typeof AuthedOnboardingRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/resources': typeof AuthedResourcesRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/directory/$userId': typeof AuthedDirectoryUserIdRoute
  '/_authed/directory/': typeof AuthedDirectoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/directory'
    | '/landing'
    | '/onboard'
    | '/onboarding'
    | '/profile'
    | '/resources'
    | '/directory/$userId'
    | '/directory/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/dashboard'
    | '/landing'
    | '/onboard'
    | '/onboarding'
    | '/profile'
    | '/resources'
    | '/'
    | '/directory/$userId'
    | '/directory'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/directory'
    | '/_authed/landing'
    | '/_authed/onboard'
    | '/_authed/onboarding'
    | '/_authed/profile'
    | '/_authed/resources'
    | '/_authed/'
    | '/_authed/directory/$userId'
    | '/_authed/directory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/resources': {
      id: '/_authed/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AuthedResourcesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboard': {
      id: '/_authed/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof AuthedOnboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/landing': {
      id: '/_authed/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof AuthedLandingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/directory': {
      id: '/_authed/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthedDirectoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/directory/': {
      id: '/_authed/directory/'
      path: '/'
      fullPath: '/directory/'
      preLoaderRoute: typeof AuthedDirectoryIndexRouteImport
      parentRoute: typeof AuthedDirectoryRoute
    }
    '/_authed/directory/$userId': {
      id: '/_authed/directory/$userId'
      path: '/$userId'
      fullPath: '/directory/$userId'
      preLoaderRoute: typeof AuthedDirectoryUserIdRouteImport
      parentRoute: typeof AuthedDirectoryRoute
    }
  }
}

interface AuthedDirectoryRouteChildren {
  AuthedDirectoryUserIdRoute: typeof AuthedDirectoryUserIdRoute
  AuthedDirectoryIndexRoute: typeof AuthedDirectoryIndexRoute
}

const AuthedDirectoryRouteChildren: AuthedDirectoryRouteChildren = {
  AuthedDirectoryUserIdRoute: AuthedDirectoryUserIdRoute,
  AuthedDirectoryIndexRoute: AuthedDirectoryIndexRoute,
}

const AuthedDirectoryRouteWithChildren = AuthedDirectoryRoute._addFileChildren(
  AuthedDirectoryRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDirectoryRoute: typeof AuthedDirectoryRouteWithChildren
  AuthedLandingRoute: typeof AuthedLandingRoute
  AuthedOnboardRoute: typeof AuthedOnboardRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedResourcesRoute: typeof AuthedResourcesRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDirectoryRoute: AuthedDirectoryRouteWithChildren,
  AuthedLandingRoute: AuthedLandingRoute,
  AuthedOnboardRoute: AuthedOnboardRoute,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedResourcesRoute: AuthedResourcesRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
