/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as AuthedDirectoryRouteImport } from './routes/_authed/directory'
import { Route as AuthedDirectoryIndexRouteImport } from './routes/_authed/directory/index'
import { Route as AuthedDirectoryUserIdRouteImport } from './routes/_authed/directory/$userId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDirectoryRoute = AuthedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDirectoryIndexRoute = AuthedDirectoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedDirectoryRoute,
} as any)
const AuthedDirectoryUserIdRoute = AuthedDirectoryUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AuthedDirectoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/directory': typeof AuthedDirectoryRouteWithChildren
  '/profile': typeof AuthedProfileRoute
  '/': typeof AuthedIndexRoute
  '/directory/$userId': typeof AuthedDirectoryUserIdRoute
  '/directory/': typeof AuthedDirectoryIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/profile': typeof AuthedProfileRoute
  '/': typeof AuthedIndexRoute
  '/directory/$userId': typeof AuthedDirectoryUserIdRoute
  '/directory': typeof AuthedDirectoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/directory': typeof AuthedDirectoryRouteWithChildren
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/directory/$userId': typeof AuthedDirectoryUserIdRoute
  '/_authed/directory/': typeof AuthedDirectoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/directory'
    | '/profile'
    | '/'
    | '/directory/$userId'
    | '/directory/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/profile' | '/' | '/directory/$userId' | '/directory'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/directory'
    | '/_authed/profile'
    | '/_authed/'
    | '/_authed/directory/$userId'
    | '/_authed/directory/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/directory': {
      id: '/_authed/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthedDirectoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/directory/': {
      id: '/_authed/directory/'
      path: '/'
      fullPath: '/directory/'
      preLoaderRoute: typeof AuthedDirectoryIndexRouteImport
      parentRoute: typeof AuthedDirectoryRoute
    }
    '/_authed/directory/$userId': {
      id: '/_authed/directory/$userId'
      path: '/$userId'
      fullPath: '/directory/$userId'
      preLoaderRoute: typeof AuthedDirectoryUserIdRouteImport
      parentRoute: typeof AuthedDirectoryRoute
    }
  }
}

interface AuthedDirectoryRouteChildren {
  AuthedDirectoryUserIdRoute: typeof AuthedDirectoryUserIdRoute
  AuthedDirectoryIndexRoute: typeof AuthedDirectoryIndexRoute
}

const AuthedDirectoryRouteChildren: AuthedDirectoryRouteChildren = {
  AuthedDirectoryUserIdRoute: AuthedDirectoryUserIdRoute,
  AuthedDirectoryIndexRoute: AuthedDirectoryIndexRoute,
}

const AuthedDirectoryRouteWithChildren = AuthedDirectoryRoute._addFileChildren(
  AuthedDirectoryRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDirectoryRoute: typeof AuthedDirectoryRouteWithChildren
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDirectoryRoute: AuthedDirectoryRouteWithChildren,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
